cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),

    url(r'^add/(?P<product_id>\d+)/$',
        views.cart_add,
        name='cart_add'),

    url(r'^remove/(?P<product_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
]   

photos/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.views.generic import TemplateView

app_name = 'photos'

urlpatterns = [
	# /photos/
	url(r'^$', views.Index , name='index'),

	# /photos/<photo_id>
	url(r'^(?P<image_id>\d+)/$', views.detail,  name='detail'),

	#/photos/search-results/
	url(r'^search-results/$', views.search, name='search'),

	#/photos/<class_id>
	url(r'^(?P<id>[0-9]+)/$', views.search_buttons , name='search_buttons'),
	# url(r'^search-img/$', views.imgsearch, name='imgsearch'),

	#/photos/user_id
	url(r'^(?P<username>\w+)/$' , views.home_page , name = 'home_page'),

]

upload/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.upload_detail, name='upload_detail'),
    ]

upload2/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.imgsearch, name='imgsearch'),
    ]

users/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.views.generic import TemplateView
import photos

app_name = 'users'

urlpatterns = [
    url(r'^register/' , views.UserRegistration , name='register'),
    url(r'^login/' , views.LoginRequest , name='login'),
    url(r'^logout/' , views.LogoutRequest , name='logout'),








]

website/urls.py
from django.conf.urls import url , include #include e7na elly benzwedha 34an ne2darn include el apps urls
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   	url(r'^admin/', admin.site.urls),
	url(r'^cart/', include('cart.urls', namespace='cart')),
	url(r'^photos/' , include('photos.urls',namespace='photos')),
	url(r'^orders/', include('orders.urls', namespace='orders')),
	url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^upload2/', include('upload2.urls', namespace='upload2')),

	url(r'^users/' , include('users.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.PHOTOS_URL, document_root=settings.PHOTOS_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


class ImageClass(models.Model):
    class_name= models.CharField(max_length=255)

    def __str__(self):
        return self.class_name


class LabelsClass(models.Model):
    label_name= models.CharField(max_length=255)

    def __str__(self):
        return self.label_name



class Photo(models.Model):
    class_name = models.ForeignKey(ImageClass, on_delete=models.CASCADE)
    label_name = models.ManyToManyField(LabelsClass)
    name = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='./photos/')
    features = models.FileField(blank = True , upload_to= './features/')
    price = models.DecimalField(max_digits=10, decimal_places=2,default = 100)

    def __str__(self):
        return self.name

class upload1(models.Model):
    product = models.FileField(upload_to='media')

photos/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    """Image upload form."""
    image = forms.ImageField()

photos/views.py
from django.shortcuts import render , redirect
from models import Photo , ImageClass , LabelsClass
import numpy as np
import tensorflow as tf
import os
from tensorflow.python.platform import gfile
import csv
from cart.forms import CartAddProductForm
from math import *
from orders.models import Order
from upload.models import Image


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
path_class = os.path.abspath(os.path.join(BASE_DIR, 'media/features'))
modelFullPath = os.path.abspath(os.path.join(BASE_DIR, 'photos/inception_dec_2015/tensorflow_inception_graph.pb'))


def create_graph():
    with tf.gfile.FastGFile(modelFullPath, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        _ = tf.import_graph_def(graph_def, name='')
def run_on_image(imagePath):
    answer = None

    if not tf.gfile.Exists(imagePath):
        tf.logging.fatal('File does not exist %s', imagePath)
        return answer

    image_data = tf.gfile.FastGFile(imagePath, 'rb').read()

    create_graph()

    with tf.Session() as sess:
        next_to_last_tensor = sess.graph.get_tensor_by_name('pool_3:0')
        # output = open(indexpath, "w")
        image_data = gfile.FastGFile(imagePath, 'rb').read()
        predictions = sess.run(next_to_last_tensor, {'DecodeJpeg/contents:0': image_data})
        queryfeature = np.squeeze(predictions)

    return queryfeature
class Searcher:
    def __init__(self, path_class):

        self.path_class = path_class

    def square_rooted(self, x):
        return round(sqrt(sum([a * a for a in x])), 5)

    def cosine_similarity(self, x, y):
        numerator = sum(a * b for a, b in zip(x, y))
        denominator = self.square_rooted(x) * self.square_rooted(y)
        return round(numerator / float(denominator), 5)
        # tgroba we faslaet bst5dam el numpy

    def cos_sim(self, a, b):

        dot_product = np.dot(a, b)
        norm_a = np.linalg.norm(a)
        norm_b = np.linalg.norm(b)
        return dot_product / (norm_a * norm_b)

    def euclidean_distance(self, x, y):
        return sqrt(sum(pow(a - b, 2) for a, b in zip(x, y)))

    def manhattan_distance(self, x, y):

        return sum(abs(a - b) for a, b in zip(x, y))

    def jaccard_similarity(self, x, y):

        intersection_cardinality = len(set.intersection(*[set(x), set(y)]))
        union_cardinality = len(set.union(*[set(x), set(y)]))
        return intersection_cardinality / float(union_cardinality)

    def search(self, queryFeatures, limit=4):

        results = {}
        results1 = {}

        for filename in os.listdir(path_class):
            with open(path_class + '/' + filename, 'r') as f:
                reader = csv.reader(f)
                for row in reader:
                    features = [float(x) for x in row[0:]]
                    d = self.cosine_similarity(features, queryFeatures)

                    results[filename[:-4]+'.jpg'] = d

                f.close()
                results1.update(results)


        results1 = sorted(results1, key=results1.get,reverse=True)

        return results1[:limit]

def detail(request, image_id):
    det_photo = Photo.objects.get(id=image_id)
    all_photo=Photo.objects.all()
    path1='media/photos'
    path2=det_photo.name
    imagePath1 = os.path.abspath(os.path.join(BASE_DIR, os.path.join(path1,path2)))

    feature = run_on_image(imagePath1)
    searcher = Searcher(path_class)
    results = searcher.search(feature)
    list_images = results
    show = Photo.objects.filter(name__in=results)
    context = {
    'det_photo': det_photo,
    'image_id': image_id,
    'results': results,
    'show' :show,
    'all_photo' :all_photo,}

    return render(request, 'photos/detail.html', context)

def Index(request):
    photos=Photo.objects.order_by('?')[:30]
    cart_product_form = CartAddProductForm()
    return render(request,'photos/index.html',{'photos':photos,'cart_product_form': cart_product_form})

def get_all_classes_and_labels_names():
    all_classes_names = []
    all_classes = ImageClass.objects.all()
    for classX in all_classes:
        all_classes_names.append(classX.class_name)

    all_labels_names = []
    all_labels = LabelsClass.objects.all()
    for label in all_labels:
        all_labels_names.append(label.label_name)

    return all_classes_names , all_labels_names

def get_all_images(name , type):
	if type == 'class':
		related_images = []
		for image_class in ImageClass.objects.all():
			if image_class.class_name == name.lower():
				related_images = image_class.photo_set.all()
				break
	if type == 'label':
		related_images = []
		for image_label in LabelsClass.objects.all():
			if image_label.label_name == name.lower():
				related_images = image_label.photo_set.all()
				break

	return related_images

def search(request):
    all_classes_names , all_labels_names = get_all_classes_and_labels_names()

	# suggested_labels = []
    list_for_each_word = []
    related_images = []
    empty = 1

    class_words_counter = 0
    more_than_one_class = []

    if request.method == "POST":
        search_text = request.POST.get("input")
        search_words = search_text.split()

        for i in range(0 , len(search_words)):
            if search_words[i] in all_labels_names:
                empty = 0

                three_words_label = search_words[i]
                two_words_label = search_words[i]

                if len(search_words) > i+3:
                    three_words_label= search_words[i]+' '+search_words[i+1]+' '+search_words[i+2]
                elif len(search_words) > i+2 :
                    two_words_label = search_words[i]+' '+search_words[i+1]

                if three_words_label in all_labels_names:
                    related_images = get_all_images(three_words_label , 'label')
                    i += 3
                elif two_words_label in all_labels_names:
                    related_images = get_all_images(two_words_label, 'label')
                    i += 2
                else:
                    related_images = get_all_images(search_words[i] , 'label')

                if len(related_images) != 0:
                    list_for_each_word.append(related_images)

            elif search_words[i] in all_classes_names:
                class_words_counter += 1
                more_than_one_class.append(ImageClass.objects.filter(class_name=search_words[i]).first())
                empty = 0
                # suggested_labels = get_labels_for_classX(search_words[i])
                related_images = get_all_images(search_words[i] , 'class')
                if len(related_images) != 0:
					list_for_each_word.append(related_images)

    if len(list_for_each_word) != 0:
            related_images = set(list_for_each_word[0])
            for s in list_for_each_word[1:]:
                related_images.intersection_update(s)


    return render(request, 'photos/search.html' , {'related_images':related_images, 'class_words_counter' : class_words_counter ,
                                                   'more_than_one_class' : more_than_one_class , 'empty':empty,
                                                  'all_classes': ImageClass.objects.all()})

def search_buttons(request , id):
	classX = ImageClass.objects.filter(id=id).first()
	images = get_all_images(classX.class_name , 'class')
	return render(request , 'photos/show_classX_images.html' , {'related_images':images})

def home_page(request , username):
    photos_of_user_orders = Photo.objects.all()
    final_recommended_photos = Photo.objects.all()
    user_uploads =  Image.objects.all()

    if request.user.is_authenticated:
        user_orders = Order.objects.filter(userid = request.user.id)
        list_of_user_orders = []
        for order in user_orders:
            list_of_user_orders.append(order.product.id)
        photos_of_user_orders = Photo.objects.filter(id__in=list_of_user_orders)

        user_uploads = Image.objects.filter(userid = request.user.id)
        list_of_user_uploads = []
        for upload in user_uploads:
            list_of_user_uploads.append(upload.product)
        photos_of_user_uploads = Photo.objects.filter(photo__in=list_of_user_uploads)

        recommended_photos = []
        for photo in photos_of_user_orders:
            feature = run_on_image(photo.photo.url[1:])
            searcher = Searcher(photo.features.url[1:])
            results = searcher.search(feature)
            recommended_photos.append(results)

        flatten_recommended_photos = [item for sublist in recommended_photos for item in sublist]


        final_recommended_photos = Photo.objects.filter(name__in=flatten_recommended_photos)

    return render(request, 'photos/user_home_page.html' , {'photos_of_user_orders':photos_of_user_orders
                                                           , 'orders_size' : len(photos_of_user_orders)
                                                           , 'photos_of_user_uploads' : user_uploads
                                                           , 'uploads_size' : len(user_uploads)
                                                           , 'final_recommended_photos' : final_recommended_photos
                                                           , 'username':request.user.username})




# def imgsearch(request):
#
#     if request.method == 'POST':
#         form = ImageUploadForm(request.POST, request.FILES)
#
#
#         if form.is_valid():
#             # id = uplo
#             # id.product.save(request.FILES['product'].name)
#
#             p = upload1(product=request.FILES['product'])
#             p.save()
#             # return HttpResponseRedirect('/photos/')
#
#     else:
#         form =  ImageUploadForm
#     return render(request, 'upload2/imgsearch.html',{'form':form})
#


    # return render(request, 'photos/imgsearch.html')






    # Do something for anonymous users.

photos/templates/photos/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>{% block title %}Pics{% endblock %}</title>
    <!-- load the path to my static files -->
    {% load staticfiles %}
    <!-- 2wel link da 34an ne2dar nesta5dem default bootstrab bs w hwa online mo4 lazem anazelo 3ndy-->
    <!-- lazem ykon abl ma link el stylesheets bta3ty 34an elly byezhar fel 2a5er by overwrite 3la elly ablo-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'photos/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>

    <nav class="navbar navbar-inverse" >
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'photos:index' %}">Pics</a>
            </div>

            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">

                </ul>

                <form class="navbar-form navbar-left" role="search" method="post" action="{% url 'photos:search' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="input" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>


                </form>


                <div class="navbar-form navbar-right">
                    {% if user.is_authenticated %}
                        <p><a href="/users/logout/">Logout</a></p>
                    {% else %}
                        <form class="navbar-form navbar-right" method="get" action="{% url 'users:login' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-default">LogIn</button>
                        </form>
                    {% endif %}
                </div>

                <div class="navbar-form navbar-right">
                    {% if user.is_authenticated %}
                    <p style="color:white;"><a href="{% url 'photos:home_page' user.username %}">{{ user.username }}</a></p>
                    {% else %}<a href="/users/register/">
                        <button class="btn btn-default">Signup</button></a>
                    {% endif %}
                </div>

                <div class="navbar-form navbar-right">
                     <div class="cart">
                      {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                          Your cart:
                          <a href="{% url 'cart:cart_detail' %}">
                            {{ total_items }} item{{ total_items|pluralize }},
                            ${{ cart.get_total_price }}
                          </a>
                        {% else %}
                           <font color="red">Your cart is empty.</font>
                        {% endif %}
                      {% endwith %}
                    </div>
                </div>

                <div class="navbar-form navbar-left">
                    {% if user.is_authenticated %}
                        <p><a href="{%url 'upload:upload_detail' %}">Upload</a></p>
                    {% else %}
                        <p><a href="/users/register/">Upload</a></p>
                    {% endif %}
                </div>
                 <!--search_by_image -->





                 <form class="navbar-form navbar-right" method="post" action="{% url 'upload2:imgsearch' %}" >
                     {% csrf_token %}

                    <button type="submit" class="btn btn-default "  >search by image</button>


                 </form>




            </div>

        </div>
    </nav>

    {% block some_page_contents %}
    {% endblock %}

</body>
</html>

photos/templates/photos/detail.html
{% extends 'photos/base.html' %}

{% block some_page_contents %}
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'photos/pins.css' %}">
    <div class="container">
        <ul>
                <!--div class="row"-->
                    {%  for photo in show %}
                    <!--div class="col-sm-4" -->
                        <li style="display: inline">
                            <div id="wrapper">
                                <div id="columns">
                                    <div class="pin">

                                            <img src="{{ photo.photo.url }}" class="img-responsive" style="float: left;"/>

                                            <form action="{% url 'cart:cart_add' photo.id %}" method="post">
                                              {{ cart_product_form }}
                                              {% csrf_token %}
                                              <input type="submit" value="Add to cart">
                                            </form>

                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    <!--/div-->
                    {% endfor %}
                <!--/--div-->
        </ul>
    </div>
{% endblock %}





    <!--<li>  {{det_photo.name}} {{results}} </li>-->

photos/templates/photos/hh.html
<h1>hager</h1>

photos/templates/photos/index.html
{% extends 'photos/base.html' %}

{% block some_page_contents %}
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'photos/pins.css' %}">
    <div class="container">
        <ul>
                <!--div class="row"-->
                    {%  for photo in photos %}
                    <!--div class="col-sm-4" -->
                        <li style="display: inline">
                            <div id="wrapper">
                                <div id="columns">
                                    <div class="pin">
                                        <a href="{% url 'photos:detail' photo.id %}" >
                                            <img src="{{ photo.photo.url }}" class="img-responsive" style="float: left;"/>

                                            <form action="{% url 'cart:cart_add' photo.id %}" method="post">
                                              {{ cart_product_form }}
                                              {% csrf_token %}
                                              <input type="submit" value="Add to cart">
                                            </form>

                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    <!--/div-->
                    {% endfor %}
                <!--/--div-->
        </ul>
    </div>
{% endblock %}

photos/templates/photos/rec.html
<h1>"page"</h1>

photos/templates/photos/recommended_images.html
{% extends 'photos/base.html' %}

{% block some_page_contents %}



{% endblock %}

photos/templates/photos/search.html
{% extends 'photos/base.html' %}

{% block some_page_contents %}

    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'photos/pins.css' %}">
    <div class="container">

        {% if empty == 0 %}
            <ul>
                {% if class_words_counter > 1 %}
                    <p>You can search for only one category at a time: </p>
                    {% for class in more_than_one_class %}
                        <button type="submit" class="btn btn-default" onclick="location.href='{% url 'photos:search_buttons' class.id %}'">{{ class.class_name}}</button>
                    {% endfor %}
                {% else %}
                    {% for image in related_images %}
                        <li style="display: inline">
                            <div id="wrapper">
                                <div id="columns">
                                    <div class="pin">
                                        <a href="{% url 'photos:detail' image.id %}" >
                                            <img src="{{ image.photo.url }}" class="img-responsive" style="float: left;"/>
                                            <form action="{% url 'cart:cart_add' image.id %}" method="post">
                                                {{ cart_product_form }}
                                                {% csrf_token %}
                                                <input type="submit" value="Add to cart">
                                            </form>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                {% endif %}
            </ul>
        {% else %}
            <p>You can only search for the for the following categories.</p>
            {% for class in all_classes %}
                <button name="class_name" type="submit" class="btn btn-default" onclick="location.href='{% url 'photos:search_buttons' class.id %}'">{{ class.class_name}}</button><br>
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}

photos/templates/photos/show_classX_images.html
{% extends 'photos/base.html' %}

{% block some_page_contents %}

    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'photos/pins.css' %}">
    <div class="container">
        <ul>
            {% for image in related_images %}
                <li style="display: inline">
                    <div id="wrapper">
                        <div id="columns">
                            <div class="pin">
                                <a href="{% url 'photos:detail' image.id %}" >
                                    <img src="{{ image.photo.url }}" class="img-responsive" style="float: left;"/>
                                    <form action="{% url 'cart:cart_add' image.id %}" method="post">
                                        {{ cart_product_form }}
                                        {% csrf_token %}
                                        <input type="submit" value="Add to cart">
                                    </form>
                                </a>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

photos/templates/photos/user_home_page.html
{% extends 'photos/base.html' %}

{% block some_page_contents %}
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'photos/pins.css' %}">
    <div class="container">
        {% if uploads_size > 0 %}
            <p>Your uploads history</p>
            <ul>
                    <!--div class="row"-->
                        {%  for photo in photos_of_user_uploads %}
                        <!--div class="col-sm-4" -->
                            <li style="display: inline">
                                <div id="wrapper">
                                    <div id="columns">
                                        <div class="pin">
                                                <img src="{{ photo.product.url }}" class="img-responsive" style="float: left;"/>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        <!--/div-->
                        {% endfor %}
                    <!--/--div-->
            </ul>
        {% else %}
            <p>You don't have any uploads.</p>
        {% endif %}


        {% if orders_size > 0 %}
            <p>Your orders history</p>
            <ul>
                    <!--div class="row"-->
                        {%  for photo in photos_of_user_orders %}
                        <!--div class="col-sm-4" -->
                            <li style="display: inline">
                                <div id="wrapper">
                                    <div id="columns">
                                        <div class="pin">
                                                <a href="{% url 'photos:detail' photo.id %}" >
                                                <img src="{{ photo.photo.url }}" class="img-responsive" style="float: left;"/>
                                                </a>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        <!--/div-->
                        {% endfor %}
                    <!--/--div-->
            </ul>
        {% else %}
            <p>You don't have any orders.</p>
        {% endif %}


        {% if orders_size > 0 %}
            <p>Recommended for you:</p>
            <ul>
                    <!--div class="row"-->
                        {%  for photo in final_recommended_photos %}
                        <!--div class="col-sm-4" -->
                            <li style="display: inline">
                                <div id="wrapper">
                                    <div id="columns">
                                        <div class="pin">
                                             <a href="{% url 'photos:detail' photo.id %}" >
                                                <img src="{{ photo.photo.url }}" class="img-responsive" style="float: left;"/>

                                                <form action="{% url 'cart:cart_add' photo.id %}" method="post">
                                                  {{ cart_product_form }}
                                                  {% csrf_token %}
                                                  <input type="submit" value="Add to cart">
                                                </form>

                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        <!--/div-->
                        {% endfor %}
                    <!--/--div-->
            </ul>
        {% else %}
            <p>No orders then no recommendations. <a href="{% url 'photos:index' %}">So go to Pics home page</a></p>
        {% endif %}


    </div>
{% endblock %}