cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),

    url(r'^add/(?P<product_id>\d+)/$',
        views.cart_add,
        name='cart_add'),

    url(r'^remove/(?P<product_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
]   

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$',
        views.order_create,
        name='order_create'),
]

photos/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.views.generic import TemplateView

app_name = 'photos'

urlpatterns = [
	# /photos/
	url(r'^$', views.Index , name='index'),

	# /photos/<photo_id>
	url(r'^(?P<image_id>\d+)/$', views.detail,  name='detail'),

	#/photos/search-results/
	url(r'^search-results/$', views.search, name='search'),

	#/photos/<class_id>
	url(r'^(?P<id>[0-9]+)/$', views.search_buttons , name='search_buttons'),
	# url(r'^search-img/$', views.imgsearch, name='imgsearch'),

	#/photos/user_id
	url(r'^(?P<username>\w+)/$' , views.home_page , name = 'home_page'),

]

website/urls.py
from django.conf.urls import url , include #include e7na elly benzwedha 34an ne2darn include el apps urls
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   	url(r'^admin/', admin.site.urls),
	url(r'^cart/', include('cart.urls', namespace='cart')),
	url(r'^photos/' , include('photos.urls',namespace='photos')),
	url(r'^orders/', include('orders.urls', namespace='orders')),
	url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^upload2/', include('upload2.urls', namespace='upload2')),

	url(r'^users/' , include('users.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.PHOTOS_URL, document_root=settings.PHOTOS_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from photos.models import Photo
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Photo, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Photo, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'detail.html', {'cart': cart})

cart/templates/detail.html
{% extends "photos/base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block some_page_contents %}
  <h1>Your shopping cart</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                  <img src="{{ PHOTOS_URL }}media/photos/{{ photo.name }}" class="img-responsive" style="float: left;"/>
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>

            <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'photos:index' %}" class="button light">Continue shopping</a>
    <a href="{% url 'orders:order_create' %}" class="button">
      Checkout
    </a>
  </p>
{% endblock %}